language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"

before_install:
  - travis_retry npm install -g npm
  - travis_retry npm install

script:
  - npm test

notifications:
  email:
    - travis@nodejitsu.com

